services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8.0.42
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: shikamaru
      MYSQL_PASSWORD: shadow
      MYSQL_ROOT_PASSWORD: shadow
    volumes:
      - .db_data:/var/lib/mysql
    ports:
      - "33066:3306"